# Generated by Django 3.1.7 on 2021-04-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210425_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travellers', models.IntegerField(default='')),
                ('hotel_name', models.CharField(default='', max_length=100)),
                ('food', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='hog',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
