# Generated by Django 3.1.7 on 2021-04-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210426_0129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='pin',
            new_name='days',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='caption',
            new_name='place',
        ),
        migrations.RemoveField(
            model_name='image',
            name='address',
        ),
        migrations.RemoveField(
            model_name='image',
            name='city',
        ),
        migrations.RemoveField(
            model_name='image',
            name='hog',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='org',
        ),
        migrations.RemoveField(
            model_name='image',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='image',
            name='state',
        ),
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
