# Generated by Django 3.1.7 on 2021-04-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210427_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='money',
            field=models.IntegerField(default='0'),
        ),
    ]
