# Generated by Django 3.1.7 on 2021-04-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_booking_user'),
        ('home', '0008_hotels'),
    ]

    operations = [
    ]
