# Generated by Django 3.1.7 on 2021-04-28 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='food',
        ),
    ]
